### ISSUE TITLE
XE4 compilation error with the latest version as of Feb 10, 2023

### ISSUE THREAD

**Issue by edwinyzh** [sempare/sempare-delphi-template-engine#102]
Thanks for the recent update, so I tried compiling the tester project with xe4 and got the following errors:

[dcc32 Error] Sempare.Template.Rtti.pas(408): E2003 Undeclared identifier: 'tkMRecord'
[dcc32 Error] Sempare.Template.Rtti.pas(715): E2003 Undeclared identifier: 'tkMRecord'

I fixed the above and got the following, and I can go this ATM.
[dcc32 Error] Sempare.Template.Evaluate.pas(178): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(188): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(200): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(205): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(227): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(302): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(322): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(355): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(360): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(431): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(709): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(809): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(822): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(833): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(838): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(861): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(955): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(985): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(1006): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(1012): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(1034): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(1044): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(1113): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(1131): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(1136): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(1145): E2037 Declaration of 'Visit' differs from previous declaration
[dcc32 Error] Sempare.Template.Evaluate.pas(1162): E2037 Declaration of 'Visit' differs from previous declaration

**Comment by sbogie-gdi** [comment]
Looks like a few places were missed in the effort to add const everywhere in commit ae5bff27b31304a8ceda6fb403279ab4962a4625

In Sempare.Template.Evaluate.pas: `TEvaluationTemplateVisitor.Visit` implementations all need a `const` added to their parameter.
In Sempare.Template.Parser.pas `TIfStmt.Create` declaration needs a `const` on `APosition`.

**Comment by darnocian** [comment]
Thanks for highlighting the issues. Reviewing the issues now.

**Comment by darnocian** [comment]
Release v1.5.1 has addressed the issues.

**Comment by edwinyzh** [comment]
Thanks! I confirm it can be built under XE4 and the test project run as expected.
