### ISSUE TITLE
For-in does not work with arrays/dynamic arrays

### ISSUE THREAD

**Issue by craigmox** [sempare/sempare-delphi-template-engine#105]
Hi, great work on this project!  I found a bug while trying to iterating through dynamic arrays with the for-in statement.  The following should output two lines "Child 1" and "Child 2" but it outputs empty strings.

```
program ArrayForIn;

uses
  Sempare.Template;

type
  TMember = record
    Name: String;
  end;

  TParent = record
    Members: TArray<TMember>;
  end;

begin
    var tpl := Template.Parse(
       '<% for member in members %>'+#13#10+
         '<% member.name %>'+
       '<% end %>');

    var parent: TParent;

    SetLength(parent.Members, 2);
    parent.Members[0].Name := 'Child 1';
    parent.Members[1].Name := 'Child 2';

    writeln(Template.Eval(tpl, parent));

    Readln;
end.
```

**Comment by darnocian** [comment]
Thank you. I’ll have a look. I thought that was covered by a test. I’ll investigate.

**Comment by craigmox** [comment]
Ah you're right here it is:

```
procedure TTestTemplateArr.TestDynArray;
var
  a: tarray<integer>;
  i: integer;
begin
  setlength(a, 5);
  for i := Low(a) to High(a) do
    a[i] := i * 2;
  Assert.AreEqual('0 2 4 6 8 ', Template.Eval('<%for i in _%><% _[i]%> <%end%>', a));
end;
```

It looks like it was intentional for `i` to be the index into the array, rather than the element value.  I had assumed it was a bug because it wasn't documented how it works, but I can understand how changing the behavior now would be a breaking change and likely frustrate others.

It looks like you may have modeled this behavior on Javascript.  Would you consider adding a new syntax `for-of`?  Example:

```
  Assert.AreEqual('0 2 4 6 8 ', Template.Eval('<%for value of _%><% value %> <%end%>', a));
```

**Comment by darnocian** [comment]
I had some time to think about it... Did a quick test on Dictionary, and realised that the 'for x in dict' actually returns a pair<key, value> when enumerating, so not what I was thinking above.

when I ran all the unit tests, the fix did fail. One way is to introduce the support as you described with the 'of'.  Another is using a feature flag, like using the context options where an option like eoForInArrayWithValues could be set. Using 'of' may be easier to use rather than requiring context config to be setup and passed, so am not opposed to the idea you suggested, and it should be fairly trivial to include.

**Comment by craigmox** [comment]
Sure, a context flag is a good idea too.  I think I prefer the `of` syntax, so that there isn't a need to go back through existing templates to be compatible with the new behavior.  But it's not that important, so either option is great.  Thanks for considering it.

**Comment by darnocian** [comment]
I've implemented basic for-of support in #109. Hope to finalise this next week.

**Comment by darnocian** [comment]
Hi Craig,

The for-of functionality is now in the dev branch. 

I'll prepare a release branch onto the main branch if you can confirm I've address the core issues.

Regards,
Conrad

**Comment by craigmox** [comment]
Thank you Conrad.  My team and I will be testing it soon, and I will let you know.

**Comment by darnocian** [comment]
Hi Craig. 

Just following up if you had a chance to confirm if the latest dev branch addressed your issues. 

I'm going to prepare the release in the meantime.

**Comment by darnocian** [comment]
Great stuff! Thanks again for validating!
