### ISSUE TITLE
Sempare.Template.Pkg unnecessarily contains FireDAC

### ISSUE THREAD

**Issue by sbogie-gdi** [sempare/sempare-delphi-template-engine#114]
Attempting to load the package results in the error
`Cannot load package 'Sempare.Template.Pkg.' It contains unit 'FireDAC.Comp.UI', which is also contained in package 'FireDAC280'...`

This is caused by the use of `FireDAC.Comp.Client` in Sempare.Template.Functions.pas without a corresponding requires in the dpk. Given nothing in Sempare.Template.Functions actually requires FireDAC (only the base TDataSet from Data.DB), it seems most effective to simply remove it from the uses.

**Comment by darnocian** [comment]
Will get PR #115 merged in soon.

**Comment by sempare** [comment]
Merged.
