### ISSUE TITLE
Regression calling `Template.Eval<T>` where T = TValue

### ISSUE THREAD

**Issue by sbogie-gdi** [sempare/sempare-delphi-template-engine#146]
Prior to the change made in c3440367557793d57840295be9d25e5d79c3545c calling `Template.Eval<TValue>` allowed access to the underlying value stored within the TValue. After the change, the root stack frame ends up with a `TValue -> TValue -> Inner Value` which cannot be properly deref'd from within the template.

This is useful when encapsulating template rendering and exposing it through e.g. an interface to other components in the system. For now we have a workaround by calling `Template.EvalWithContext` which takes a `TTemplateValue` directly, but this doesn't work if trying to route through the new `TTemplateRegistry`.

A possible approach which also avoids the overhead of the previous `AsType<TValue>` call would be something like the following:
```diff
diff --git a/src/Sempare.Template.pas b/src/Sempare.Template.pas
index 902a773..934bfa8 100644
--- a/src/Sempare.Template.pas
+++ b/src/Sempare.Template.pas
@@ -199,8 +199,11 @@ begin
 end;

 class procedure Template.Eval<T>(const AContext: ITemplateContext; const ATemplate: ITemplate; const AValue: T; const AStream: TStream);
+type
+  PTemplateValue = ^TTemplateValue;
 var
   LTemplateVisitor: IEvaluationTemplateVisitor;
+  LValue: TTemplateValue;
 begin
 {$IFNDEF SEMPARE_TEMPLATE_CONFIRM_LICENSE}
 {$IFDEF MSWINDOWS}
@@ -216,7 +219,11 @@ begin
   end;
 {$ENDIF}
 {$ENDIF}
-  LTemplateVisitor := TEvaluationTemplateVisitor.Create(AContext, '', TTemplateValue.From<T>(AValue), AStream);
+  if TypeInfo(T) = TypeInfo(TTemplateValue) then
+    LValue := PTemplateValue(@AValue)^
+  else
+    LValue := TTemplateValue.From(AValue);
+  LTemplateVisitor := TEvaluationTemplateVisitor.Create(AContext, '', LValue, AStream);
   AcceptVisitor(ATemplate, LTemplateVisitor);
 end;

```

Sample test case:
```delphi
procedure TTestTemplateDeref.TestDerefValue;
var
  rec: record a: string end;
begin
  rec.a := '1234';
  Test(TTemplateValue.From(rec), '"1234"', '"<% a %>"');
end;
```

**Comment by darnocian** [comment]
Hmm. I'll review these again. There are quite a few overloads, and some may not be optimal. I saw while tracing how the TValue got wrapped again. I'll check if this can be minimised.

**Comment by darnocian** [comment]
Will be in next release. Currently in the dev branch.

**Comment by darnocian** [comment]
I am just testing 1.7.2 now on older Delphi versions that includes some of the fixes for the issues reported. The fixes have been sitting in the dev branch for a while. Apologies for the delay.
