### ISSUE TITLE
Seems to be mistake in documentation

### ISSUE THREAD

**Issue by mWaltari** [sempare/sempare-delphi-template-engine#33]
at **https://github.com/sempare/sempare-delphi-template-engine/blob/master/docs/tricks.md**

type
    TRecord = record
        v1 : string;
        v2 : string;
        v3 : string;
    end;
begin
    var rec : TRecord;
    with rec do begin
        v1 := 'a';
        v2 := 'b';
        v3 := 'c';
        v4 := 'd';
    end;
    writeln(Template.Eval('<%for i := 1 to 4 %><% v['v' + i] %><% end %>'));
end;

^

v4 missing from TRecord

**Comment by sempare** [comment]
Thank you for reporting the error.

**Comment by sempare** [comment]
After fixing in haste and then reviewing properly, I noticed another mistake. 'rec' was not passed to the Eval function either.

**Comment by sempare** [comment]
Thanks again.
