### ISSUE TITLE
error when calling AddFunctions

### ISSUE THREAD

**Issue by edwinyzh** [sempare/sempare-delphi-template-engine#58]
I'm trying to use custom utility functions, but stuck at the `AddFunctions` stage and have no clue...

The details of the error:
main thread ($bbc):
005392a0 +000 prog1.exe System.Rtti                       4643   +0 TRttiType.GetHandle
0053a194 +004 prog1.exe System.Rtti                       4841   +1 TRttiType.GetTypeKind
014b0467 +067 prog1.exe Sempare.Template.Functions         105   +1 TTemplateFunctions.Add
014b0682 +062 prog1.exe Sempare.Template.Functions         131   +3 TTemplateFunctions.AddFunctions
01fa3fca +11a prog1.exe SempareTemplateSiteCompilerImplU   826  +16 TSempareTemplateSiteCompilerImpl.AfterConstruction

The class in question:
```
  // Custom utility functions for the template script
  TTmplFunctions = class
  public
    class function InsertImage(aSiteRootRelativeImgPath, aAlt, aWidth, aHeight: string): string; static;
    class procedure SetThemeData(const aThemeData: TThemeData); static;
  end;

```

**Comment by darnocian** [comment]
```var ctx:=template.context;
ctx.addfunctions(TTmplFunctions);
 
gtpl := template.parse(ctx, '....');

writeln(Template.Eval(Ctx, GTpl, ldata));
```

does the above make sense?

**Comment by darnocian** [comment]
Ah, sorry, I didn't appreciate the issue you highlighted...

All helpers are expected to be functions... so they should return something.

maybe change SetThemeData to something like:
 class function SetThemeData(const aThemeData: TThemeData) : string; static;

and return empty string for now.

I think I can fix this to do so automatically.

**Comment by edwinyzh** [comment]
Making SetThemeData to return `string` helped. Maybe in the future to remove this limit ;)
Thanks!

**Comment by sempare** [comment]
The issue in supporting procedures in the template engine is that it starts to violate the core principle. Data should be presented to the template engine rather than the template engine mutating and updating data. Functions should generally be used for formatting purposes.

Supporting procedures can be done however.
