### ISSUE TITLE
named parameter support for custom functions

### ISSUE THREAD

**Issue by sempare** [sempare/sempare-delphi-template-engine#66]
allow custom functions to be called, something like:

`<% doPrint({ "name" : "peter", "age": 10}) %>`

Args can be in any order:

`<% doPrint({ "age": 10, "name" : "peter" }) %>`

```
function doPrint(const name:string; const age:integer) : string;
begin
    exit(format('%s %d', [name, age])];
end;
```

**Comment by darnocian** [comment]
related branch is json_support, but will need to review as it is quite old

**Comment by darnocian** [comment]
v1.7.2 includes the initial json / map like variable support, but doesn't support passing to functions yet.
