### ISSUE TITLE
Support pipeline function calls

### ISSUE THREAD

**Issue by sempare** [sempare/sempare-delphi-template-engine#67]
e.g.

`<% date_value | format_date('yyyy-mm-dd') %>`

**Comment by sempare** [comment]
the function being piped to would require the first parameter to be the value. arguments in the pipe call would be 2nd parameter onwards. 

e.g. <% date_value | format_date('yyyy-mm-dd') %> = <% format_date(date_value , 'yyyy-mm-dd') %>

**Comment by darnocian** [comment]
additional complexity that is probably not required. just nest function calls...
