### ISSUE TITLE
Abstract variable resolution away from RTTI

### ISSUE THREAD

**Issue by darnocian** [sempare/sempare-delphi-template-engine#70]
The use of RTTI is pretty effective, however it may provide some overhead. Providing an abstraction for the resolution, the developer can use the RTTI by default, or override with their own data dereferencing mechanisms.

**Comment by sempare** [comment]
There was a discussion that this may be useful if RTTI performance was a concern. 
It may also be useful to review in terms of FPC compatibility.

**Comment by sempare** [comment]
There is quite a lot of functionality relying on RTTI. It may be interesting to try to do this, but it will remove a lot of the functionality in the library. e.g. enumerations, checking if objects are non-empty, etc.
