### ISSUE TITLE
Support for 'extends' similar to jinja2

### ISSUE THREAD

**Issue by darnocian** [sempare/sempare-delphi-template-engine#72]
Currently, inclusion is done using the 'include' paradigm.
parent.tpl:
```
<% include('header.tpl') %>
<% include(content_tpl) %>
<% include('footer.tpl') %>
```

Python jinja2 has another 'include' mechanism using 'extends'  and 'block'.

parent.tpl:
```
<% body 'content' %>parent template content<% end %>
```
child.tpl
```
<% extends "parent.tpl" %>
<% body 'content' %>child template  content<% end %>
```
child_with_parent.tpl
```
<% extends "parent.tpl" %>
<% body 'content' %>child template  content <% super %><% end %>
```

rendering child.tpl:
```
child template  content
```
rendering child_with_parent.tpl:
```
child template content parent template  content
```

**Comment by craigmox** [comment]
Love this idea!  We are currently using a hacky solution of merging templates programmatically to try to accomplish this, but this is way more elegant and easier to comprehend.  If you ever return to this, we would definitely use it.

**Comment by darnocian** [comment]
The branch extends_super_support has the feature working now. Still reviewing however. (Decided not to implement the super/inherited feature however as it is more complex)
